helmDefaults:
  createNamespace: true
  timeout: 300
  wait: false

repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.13.1
  set:
  - name: installCRDs
    value: true
