replicaCount: 1

image:
  repository: 648921681300.dkr.ecr.eu-central-1.amazonaws.com/gqbooksui
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  name: http
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
  hosts:
    - host: gqbooksui.citizix.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: gqbooksui-tls
     hosts:
       - gqbooksui.citizix.com

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
