// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	Title  string  `json:"title"`
	Author string  `json:"author"`
	Pages  []*Page `json:"pages"`
}

type Combined struct {
	Index      *int    `json:"index,omitempty"`
	Token      *string `json:"token,omitempty"`
	Content    string  `json:"content"`
	IsTappable bool    `json:"isTappable"`
}

type Page struct {
	PageIndex     int         `json:"pageIndex"`
	Content       string      `json:"content"`
	RefinedTokens []*Combined `json:"refined_tokens"`
	Tokens        []*Token    `json:"tokens"`
}

type Token struct {
	Position []int  `json:"position"`
	Value    string `json:"value"`
}
