// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	Title  string  `json:"title"`
	Author string  `json:"author"`
	Pages  []*Page `json:"pages"`
}

type Page struct {
	PageIndex int      `json:"pageIndex"`
	Content   string   `json:"content"`
	Tokens    []*Token `json:"tokens"`
}

type Token struct {
	Position []int  `json:"position"`
	Value    string `json:"value"`
}
