name: Backend app deploy to EKS

on: {}
  # push:
  #   branches:
  #   - main
  # pull_request:
  #   branches: [ "main" ]

jobs:
  deploy-ui:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: gqbooksui
        IMAGE_TAG: v0.1.0
      working-directory: web
      run: |
        docker build --build-arg API_URL=https://api.gqbooks.citizix.com/query -t ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG} . -f Dockerfile
        docker push ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

    # - name: Update kube config
    #   run: aws eks update-kubeconfig --name devops-cluster

    # - name: Deploy to EKS
    #   run: |
    #     kubectl apply -f deployment.yaml
    #     kubectl apply -f service.yaml
